### PR TITLE
More support for macOS

### PR DESCRIPTION
**Pull request by ryota2357**
Thank you for the great tool!!

Currently:

- Release x86 macOS binary.
- Tested on arm64 (ci). (`macos-latest` is macOS 14 Arm64, ref: [actions/runner-images#available-image](https://github.com/actions/runner-images?tab=readme-ov-file#available-images))

This PR allows testing on x86 and adds arm64 releases.

I have tested this on both x84 and arm64.

### CODE REVIEW

**Comment by xyproto** [comment]
Thanks for the PR! Only the latest version of Go needs to be supported, if it makes things easier.

**Comment by ryota2357** [comment]
Thank you for your quick response!
I have updated the dependency versions.

I could not understand why CI was failing. I hope this update will solve the problem...

**Comment by ryota2357** [comment]
I'm sorry, I didn't know that macos-14-large needs to payment.
I will remove it.

**Comment by xyproto** [comment]
I updated the CI configuration in the main branch to use the latest versions, then rebased this branch.

**Comment by xyproto** [comment]
I wasn't aware of the macos-14-large payment either.

Thanks for the work on this PR. :+1:

**Comment by xyproto** [comment]
Merged, thanks!

Unfortunately, I see now that I gave the commit a bit inaccurate description. I can mention the correct thing in the changelog / next release.

**Pull request merged**
